source "https://rubygems.org"

gem 'avro'
gem 'nypl_log_formatter'
gem 'aws-sdk-kms'


group :test do
  gem "test-unit"
  gem "rspec"
  gem 'webmock'
end

gem "json", "~> 2.3"

gem "pry-nav", "~> 0.3.0"
