AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'is-research'

Resources:
  IsResearch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handle_event
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v0.1/{type}/{nyplSource}/{id}/is-research
            Method: get
      Runtime: ruby2.7
      Timeout: 10
      Environment:
        Variables:
          PLATFORM_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
          NYPL_OAUTH_URL: https://isso.nypl.org/
          NYPL_OAUTH_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDB3lYTYU04av4OnbNQIBEIAvSBmocuDifqaR7m/oz1sww7EOT5AmdIDHcN3BjLJFeEr29tWjmVGQieCtuCBG0mg=
          NYPL_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxTbYOpZKkGXvj0PVECARCAQwB5D28eOHEM97D5k6DnLau4hBBXuuQs8IgMcAFb4bBh2nNZobeRirbOogNLmkIVk4HI8o/BoMBhLKkIzqvWDNXDeLM=
          NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com/nypl-core-objects-mapping-production/
          LOG_LEVEL: DEBUG
