AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'is-research'

Resources:
  IsResearch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handle_event
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v0.1/{type}/{nyplSource}/{id}/is-research
            Method: get
      Runtime: ruby2.7
      Timeout: 10
      Environment:
        Variables:
          PLATFORM_API_BASE_URL: https://dev-platform.nypl.org/api/v0.1/
          NYPL_OAUTH_URL: https://isso.nypl.org/
          NYPL_OAUTH_ID: AQECAHjqALewp8JBJNxIQvR4oY795dyG7INaGR1glMsTEgetggAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBYrzA0rotNRV+0dMAIBEIAvGeyPXEKVTIlR+vzIs5h/0ojU/3TH3R8HX3h3xHCZp76m7mVzyRDNyREPFwq45TI=
          NYPL_OAUTH_SECRET: AQECAHjqALewp8JBJNxIQvR4oY795dyG7INaGR1glMsTEgetggAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzvLVLGEyP0EuIQC9YCARCAQ1AKv2geABsSFPvtI1JWX6YMbL348GLXhgK/dCrYs6aMQrufTjSlUi2ytOvbJpcSkPqDxHyfpjnfzBI7lGSVKP7D3mA=
          NYPL_CORE_S3_BASE_URL: https://s3.amazonaws.com/nypl-core-objects-mapping-production/
          LOG_LEVEL: DEBUG
