swagger: '2.0'
info:
 version: '0.1'
 title: Is Research Service
 description: Ending point for querying if an item is research
basePath: /api/v0.1
schemes:
 - https
paths:
  /items/{nyplSource}/{id}/is-research:
    parameters:
    - name: nyplSource
      in: path
      required: true
      type: string
      description: the nypl source
    - name: id
      in: path
      required: true
      type: string
      description: the item id
    get:
      tags:
       - items
      summary: Submit a request to determine if provided item is research
      produces:
       - application/json
      consumes:
       - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: "#/definitions/IsResearchResponse"
  /bibs/{nyplSource}/{id}/is-research:
    parameters:
    - name: nyplSource
      in: path
      required: true
      type: string
      description: the nypl source
    - name: id
      in: path
      required: true
      type: string
      description: the bib id
    get:
      tags:
       - bibs
      summary: Submit a request to determine if provided bib is research
      produces:
       - application/json
      consumes:
       - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: "#/definitions/IsResearchResponse"
definitions:
  IsResearchResponse:
    type: object
    properties:
      success:
        type: boolean
        example: true
      result:
        type: object
        properties:
          nyplSource:
            type: string
          id:
            type: string
          isResearch:
            type: boolean
