name: Deploy QA

on:
  push:
    branches: [ "qa" ]

jobs:
  deploy-qa:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/qa'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - name: Package app
        run: bash provisioning/package.sh
      - uses: hashicorp/setup-terraform@v2
      - name: Deploy app to QA
        run: |
          terraform -chdir=provisioning/qa init -input=false
          terraform -chdir=provisioning/qa apply -auto-approve -input=false
